name: Workflow CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '50 23 * * *' # executado todo dia 23:50 UTC

jobs:
  push-job:             
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '8.x'


  cron-job:            
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '8.x'